---
title: "jy2947-Dec15"
author: "Jiawei Ye"
date: "December 15, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(HH) # For VIF function # or use car::vif(fit_rs)
library("leaps") # Stepwise and test-based criteria
library(modelr) # add predictions and cross-validation
library(caret)
library(glmnet)
```

###The final model we decided
```{r from_load_to_model}
#load
cancer_reg = read_csv("./data/Cancer_Registry.csv") %>%
  janitor::clean_names() %>%
  dplyr::select(target_death_rate, everything()) %>%
  separate(geography, into = c("county", "state"), sep = ", ") %>% 
  mutate(county = str_replace(county, " ", ""))

#exclude variables with a lot missing data, categorical variables and high collinearity variables
cancer_reg_tidy = 
  cancer_reg %>% 
  dplyr::select(-pct_employed16_over, -pct_some_col18_24, -pct_private_coverage_alone, #missing data
                -county, -state, -binned_inc, -avg_ann_count, -avg_deaths_per_year) %>%   #categorical, colinearity
  dplyr::select(-med_income, -median_age_female, -pct_emp_priv_coverage, 
                -pct_public_coverage, -pct_private_coverage,  -poverty_percent, 
                -pct_hs25_over, -percent_married) %>% #colinearity
  mutate(pct_nonwhite = 1 - pct_white)

# define full and null sets for forward, backward, both ways search procedures
null = lm(target_death_rate ~ 1, data = cancer_reg_tidy)

full = lm(target_death_rate ~ ., data = cancer_reg_tidy)

# forward
step(null, scope = list(lower = null, upper = full), direction = "forward")
fit_forward = lm(formula = target_death_rate ~ pct_bach_deg25_over + incidence_rate + 
    pct_public_coverage_alone + pct_other_race + pct_white + 
    pct_hs18_24 + median_age_male + birth_rate + pct_married_households + 
    pct_unemployed16_over + pop_est2015, data = cancer_reg_tidy)
##11 predictor model with 2 not significant, R^2(adj) = 0.4988
summary(fit_forward) 

# backward
step(full, data = cancer_reg_tidy, direction="backward")
fit_backward = lm(formula = target_death_rate ~ incidence_rate + pop_est2015 + 
    median_age_male + pct_hs18_24 + pct_bach_deg25_over + pct_unemployed16_over + 
    pct_public_coverage_alone + pct_white + pct_other_race + 
    pct_married_households + birth_rate, data = cancer_reg_tidy)
##same model as forward

#both directions
step(null, scope = list(upper=full), data = cancer_reg_tidy, direction = "both")
fit_both_dir = lm(formula = target_death_rate ~ pct_bach_deg25_over + incidence_rate + 
    pct_public_coverage_alone + pct_other_race + pct_white + 
    pct_hs18_24 + median_age_male + birth_rate + pct_married_households + 
    pct_unemployed16_over + pop_est2015, data = cancer_reg_tidy)
##same model as forward, backward

#criterion based
best = function(model, ...) {

  subsets <- regsubsets(formula(model), nvmax = 19, model.frame(model), ...)
  subsets <- with(summary(subsets), cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))
  
  return(subsets)
} 
cp_r2_df = best(full, nbest = 1)
#cp_r2_df %>% as.data.frame() %>% filter(p == 11|p ==12) %>% View()
cp_r2_df 

fit_cp = lm(target_death_rate ~ incidence_rate + pop_est2015 + median_age_male + pct_hs18_24 + 
              pct_bach_deg25_over +  pct_unemployed16_over + pct_public_coverage_alone + pct_white + pct_other_race +
              pct_married_households + birth_rate , data = cancer_reg_tidy)
##minimum cp model is a 11 predictor model with cp = 6.55, adj R2=0.498808

fit_r2 = lm(target_death_rate ~ incidence_rate + pop_est2015 + median_age_male + pct_hs18_24 + pct_no_hs18_24 +
              pct_bach_deg25_over +  pct_unemployed16_over + pct_public_coverage_alone + pct_white + pct_other_race +
              pct_married_households + birth_rate , data = cancer_reg_tidy)
##maximum adjusted R2 model is a 12 predictor model with cp = 7.5, adj R2 = 0.498817

##The final model based on small increase of adjusted R2 and not too large cp
#cp_r2_df %>% as.data.frame() %>%  filter(p == 7)

model_7 = lm(target_death_rate ~ incidence_rate + median_age_male + pct_hs18_24 + pct_bach_deg25_over +
               pct_public_coverage_alone + pct_other_race + pct_married_households, data = cancer_reg_tidy)
#residual covariate plot
plot(cancer_reg_tidy$incidence_rate, model_7$residuals)
abline(h=0, lwd=2, col=2)
plot(cancer_reg_tidy$median_age_male, model_7$residuals)
abline(h=0, lwd=2, col=2)
plot(cancer_reg_tidy$pct_hs18_24, model_7$residuals)
abline(h=0, lwd=2, col=2)
plot(cancer_reg_tidy$pct_bach_deg25_over, model_7$residuals)
abline(h=0, lwd=2, col=2)
plot(cancer_reg_tidy$pct_public_coverage_alone, model_7$residuals)
abline(h=0, lwd=2, col=2)
plot(cancer_reg_tidy$pct_other_race, model_7$residuals)
abline(h=0, lwd=2, col=2)
plot(cancer_reg_tidy$pct_married_households, model_7$residuals)
abline(h=0, lwd=2, col=2)

#remove outlier in Y and fit see the changes in Y
```

### Ridge
```{r}
grid = 10^seq(5,-2, length=100)
ridge_cancer = 
  lm.ridge(target_death_rate ~ incidence_rate + median_age_male + pct_hs18_24 + pct_bach_deg25_over +
               pct_public_coverage_alone + pct_other_race + pct_married_households, data = cancer_reg_tidy, lambda = grid)
dim(coef(ridge_cancer))

#coef for 10^5
coef(ridge_cancer)[1,]

# coeffcients for 10^-2
coef(ridge_cancer)[100,]
```

```{r}
response = 
  cancer_reg %>% 
  dplyr::select(target_death_rate, incidence_rate, median_age_male, pct_hs18_24, pct_bach_deg25_over,
               pct_public_coverage_alone, pct_other_race, pct_married_households) %>% 
#  drop_na() %>% 
  dplyr::select(target_death_rate) %>% 
  as.matrix()

predictors = 
  cancer_reg %>% 
  dplyr::select(target_death_rate, incidence_rate, median_age_male, pct_hs18_24, pct_bach_deg25_over,
               pct_public_coverage_alone, pct_other_race, pct_married_households) %>% 
#  drop_na() %>% 
  dplyr::select(-target_death_rate) %>% 
  as.matrix()

ridge_cancer_1 = glmnet(predictors, response, alpha = 0, lambda = grid)
dim(coef(ridge_cancer_1))

ridge_cancer_1$lambda[50] 
coef(ridge_cancer_1)[,50]
```
###Ridge CV
```{r}

set.seed(1)

cancer_train = sample(1:nrow(predictors),nrow(predictors)/2)

cancer_test = (-cancer_train)

response_test = response[cancer_test]


# Use build-in CV function; performs a 10-fold validation by default
# glmnet() generates it's own lambda sequence

set.seed(2)
cv_out = cv.glmnet(predictors[cancer_train,], response[cancer_train], alpha=0)
plot(cv_out)


# cv.glmnet() object contains the mean cross-validation error (cvm),
# lambda min that gives the minimum cvm, etc.
cv_out
best_lambda = cv_out$lambda.min
best_lambda       


# Re-fit the model with the min lambda value, look at the coeff and MSE
#ridge_pred = predict(ridge.cv, s=best_lambda, new_pred = predictors[cancer_test,])
#mean((ridge_pred - response_test)^2)


# Ridge regression using all observations and 'best' lambda
ridge_pred = glmnet(predictors, response, alpha = 0, lambda = best_lambda)

#Compare LS method and ridge
compare_ridge_ls = cbind(coef(model_7), coef(ridge_pred))
colnames(compare_ridge_ls) <- c("LS", "Ridge")
compare_ridge_ls

```

###Confounding
```{r}
confounding_inci = lm(target_death_rate ~ median_age_male + pct_hs18_24 + pct_bach_deg25_over +
               pct_public_coverage_alone + pct_other_race + pct_married_households, data = cancer_reg_tidy) 
df_c_inci = as.data.frame(coef(confounding_inci)) %>% rownames_to_column()

confounding_age = lm(target_death_rate ~ incidence_rate + pct_hs18_24 + pct_bach_deg25_over +
               pct_public_coverage_alone + pct_other_race + pct_married_households, data = cancer_reg_tidy)
df_c_age = as.data.frame(coef(confounding_age)) %>% rownames_to_column()
confounding_hs18_24 = lm(target_death_rate ~ incidence_rate + median_age_male + pct_bach_deg25_over +
               pct_public_coverage_alone + pct_other_race + pct_married_households, data = cancer_reg_tidy)
df_c_hs18 = as.data.frame(coef(confounding_hs18_24)) %>% rownames_to_column()
confounding_bach = lm(target_death_rate ~ incidence_rate + median_age_male + pct_hs18_24 + 
               pct_public_coverage_alone + pct_other_race + pct_married_households, data = cancer_reg_tidy)
df_c_bach = as.data.frame(coef(confounding_bach)) %>% rownames_to_column()
confounding_coverage =lm(target_death_rate ~ incidence_rate + median_age_male + pct_hs18_24 + pct_bach_deg25_over +
               pct_other_race + pct_married_households, data = cancer_reg_tidy)
df_c_cov = as.data.frame(coef(confounding_coverage)) %>% rownames_to_column()
confounding_other_race = lm(target_death_rate ~ incidence_rate + median_age_male + pct_hs18_24 +
                            pct_bach_deg25_over + pct_public_coverage_alone + pct_married_households, data =
                            cancer_reg_tidy)
df_c_or = as.data.frame(coef(confounding_other_race)) %>% rownames_to_column()
confounding_marriage = lm(target_death_rate ~ incidence_rate + median_age_male + pct_hs18_24 +
                            pct_bach_deg25_over + pct_public_coverage_alone + pct_other_race, data = 
                            cancer_reg_tidy)
df_c_marr = as.data.frame(coef(confounding_marriage)) %>% rownames_to_column()

coeff_conf = coef(model_7)
coeff_conf = as.data.frame(coeff_conf) %>% 
  rownames_to_column() %>% 
  left_join(df_c_inci, by = "rowname") %>% 
  left_join(df_c_age, by = "rowname") %>%
  left_join(df_c_hs18, by = "rowname") %>%
  left_join(df_c_bach, by = "rowname") %>%
  left_join(df_c_cov, by = "rowname") %>%
  left_join(df_c_or, by = "rowname") %>%
  left_join(df_c_marr, by = "rowname") %>% 
  mutate(plus_10 = coeff_conf * 1.1, 
         minus_10 = coeff_conf * 0.9)


```

