---
title: "Model_jh4054"
author: "Joy Hsu"
date: "12/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE,
  warning = FALSE)

library(tidyverse)
```

```{r}
cancer_reg = read_csv("./data/Cancer_Registry.csv") %>%
  janitor::clean_names() %>%
  select(target_death_rate, everything()) %>%
  separate(geography, into = c("county", "state"), sep = ", ") %>% 
  mutate(
    avg_deaths_per_year = as.numeric(avg_deaths_per_year),
    med_income = as.numeric(med_income),
    pop_est2015 = as.numeric(med_income),
    county = str_replace(county, " ", ""),
    log_med_income = log(med_income))
```

### Explore correlations

```{r}
# corrplot::corrplot(cancer_reg)

str(cancer_reg)

cancer_reg %>% 
  select(-county, -binned_inc, -state) %>% 
  select(pct_ , med_income, poverty_percent) %>% GGally::ggpairs()

cancer_reg %>% 
  ggplot(aes(x = log(pct_hs18_24), y = target_death_rate)) +
  geom_point()
```

### Variables to Transform

### Collinear Variables

1) med_income, poverty_percent. Keep *poverty_percent*, stronger linear rel with explanatory variable

2) Edudation variables

```{r}
tobacco_2013 = read_csv(file = "./BRFD_tobacco_2010_present.csv") %>% 
  janitor::clean_names() %>% 
  filter(response == "Never", year == "2013") %>% 
  dplyr::select(year = "year", st = "location_desc", response, percent_never = "data_value") %>%
  mutate(
    percent_smoke = as.numeric(100 - percent_never),
    year = as.numeric(year)) %>% 
  dplyr::select(st, percent_smoke)
```

