---
title: "As5697_tidying_and_exploratory"
author: "Apoorva Srinivasan"
date: "12/10/2018"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
library("leaps")
library(faraway)
library(caret)
library(broom)
```

###Data loading
```{r}
cancer_reg = read_csv("./data/Cancer_Registry.csv") %>%
  janitor::clean_names() %>%
  select(target_death_rate, everything()) %>%
  separate(geography, into = c("county", "state"), sep = ",")
```

There are in total `r ncol(cancer_reg)` variables  and `r nrow(cancer_reg)`observations in the dataset. 


Our outcome of interest is __target_death_rate__

###dealing with missing data
```{r}
#missing data

#colSums(is.na(cancer_reg))

##pct_some_col18_24 has 2285 NAs, pct_employed_coverage_alone has 609 NA, pct_employed16_over has 152 NAs


missing_value = sapply(cancer_reg[1:34], function(x) sum(length(which(is.na(x)))))


# Percentage of missing value
percentage_missing = sapply(cancer_reg[1:34], function(x) sum(length(which(is.na(x)))) / nrow(cancer_reg))
percentage_missing %>% data.frame()

##getting rid of variables with missing values.

cancer_reg = cancer_reg %>% select(-pct_some_col18_24, -pct_private_coverage_alone, -binned_inc, -median_age) 

  ##removed binned_inc since we already have median income and median age since it is avg of median age female and male. so we'll build model with those those factors instead. ##age+gender


##percentage missing for pct_employed16_over is  ~5%, checking to see if its correlated with the outcome 
reg = lm(target_death_rate~pct_employed16_over, data = cancer_reg) %>%
  summary()

##Since the p-value is small, we will retain pct_employed16_over

cancer_reg = cancer_reg %>% select(-county, -state) %>%
  mutate(mortality = avg_deaths_per_year/pop_est2015, prevalence = avg_ann_count/pop_est2015) %>%
  select(-pop_est2015, -avg_ann_count, -avg_deaths_per_year) %>%
 mutate(study_per_cap =  
        as.factor(ifelse(study_per_cap == 0, "none", 
                         ifelse(study_per_cap < quantile(study_per_cap, .25), "low",
                         ifelse(study_per_cap < quantile(study_per_cap, .5), "medium" ,
                                ifelse(study_per_cap < quantile(study_per_cap, .75), "high", "very high")))))) %>%
  mutate(pct_non_white = pct_black+ pct_asian + pct_other_race) %>%
  select(-pct_black, -pct_asian, -pct_other_race) ##since the number of whites are a lot higher, putting the other minorities under a single variable.

  ##Since count itself can be misleading, taking proportion will give us a better model. 
 ##removed state and county variables since we're building a predictive model, area doesn't really matter.
 ##changed study_per_cap to factor variable
  

```

Now we're left with `r ncol(cancer_reg)` variables

###exploratory analysis


```{r}
hist(cancer_reg$target_death_rate) #outcome is normally distributed
hist(cancer_reg$pct_private_coverage)
hist(cancer_reg$pct_public_coverage)
hist(cancer_reg$pct_emp_priv_coverage)
hist(cancer_reg$pct_public_coverage_alone)
hist(cancer_reg$incidence_rate) ##right skewed
hist(cancer_reg$med_income) #somewhat right skewed-mostly ok
hist(cancer_reg$poverty_percent)
hist(cancer_reg$median_age_male)
hist(cancer_reg$median_age_female)
hist(cancer_reg$avg_household_size) ##left skewed
hist(cancer_reg$percent_married)
hist(cancer_reg$pct_no_hs18_24) #somehwat right
hist(cancer_reg$pct_hs18_24)
hist(cancer_reg$pct_bach_deg18_24)#right skewed
hist(cancer_reg$pct_hs25_over)
hist(cancer_reg$pct_bach_deg25_over)
hist(cancer_reg$pct_employed16_over)
hist(cancer_reg$pct_unemployed16_over)
hist(cancer_reg$pct_white) #left  skewed
hist(cancer_reg$pct_non_white) #right skewed
hist(cancer_reg$pct_married_households)
hist(cancer_reg$birth_rate)
hist(cancer_reg$mortality)
hist(cancer_reg$prevalence) #right skewed

##they are all almost normally distributed
```





###descriptive statistics

```{r}
cont_var = dplyr::select(cancer_reg, target_death_rate, everything(), -c(study_per_cap))
knitr::kable(summary(cont_var), caption = "descriptive statistics for continuous variables")
```



Choose varibles from coverage, education, employment based on best fit.

###coverage
```{r}
multi.fit = lm(target_death_rate ~ ., data = cancer_reg)
summary(multi.fit)


reg1 = lm(target_death_rate~pct_private_coverage, data = cancer_reg)
reg2 = lm(target_death_rate~pct_emp_priv_coverage, data = cancer_reg)
reg3 = lm(target_death_rate~pct_public_coverage, data = cancer_reg)
reg4 = lm(target_death_rate~pct_public_coverage_alone , data = cancer_reg)


plot(cancer_reg$pct_private_coverage, cancer_reg$target_death_rate)
abline(reg1,lwd = 2,col = 2)

plot(cancer_reg$pct_emp_priv_coverage, cancer_reg$target_death_rate)
abline(reg2,lwd = 2,col = 2)
plot(cancer_reg$pct_public_coverage, cancer_reg$target_death_rate)
abline(reg3,lwd = 2,col = 2)
plot(cancer_reg$pct_public_coverage_alone, cancer_reg$target_death_rate)
abline(reg4,lwd = 2,col = 2)
```

